# 1. Services
services:
    
    # Laravel
    laravel:
        container_name: CPA-Laravel
        build:
            context: ./vendor/laravel/sail/runtimes/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.2/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.laravel.rule=Host(`scyba.com`)"
            - "traefik.http.routers.laravel.entrypoints=laravel"
            - "traefik.http.routers.laravel.tls.certresolver=myresolver"
            - "traefik.http.services.laravel.loadbalancer.server.port=80"
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql

    # Traefik
    traefik:
        image: traefik
        container_name: CPA-Traefik
        command:
            # General
            - "--log.level=INFO"
            - "--providers.docker=true"
            - "--providers.docker.exposedByDefault=false"
            # MyResolver
            - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
            - "--certificatesresolvers.myresolver.acme.email=samuel.kowalsky@freenet.de"
            - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
            # Entrypoint: Laravel
            - "--entrypoints.laravel.address=:8000"
            - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=laravel"
            # Entrypoint: PhpMyAdmin2
            - "--entrypoints.phpmyadmin2.address=:8001"
            - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=phpmyadmin2"
            # Redirect http://laravel to https://laravel
            - "--entryPoints.laravel.http.redirections.entryPoint.to=laravel"
            - "--entryPoints.laravel.http.redirections.entryPoint.scheme=https"
            - "--entryPoints.laravel.http.redirections.entrypoint.permanent=true"
        ports:
            - "8000:8000"
            - "8001:8001"
        networks:
            - sail
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
            - "./../lamp/.letsencrypt:/letsencrypt"
        restart: always

    # MySQL
    mysql:
        container_name: CPA-Mysql
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s

    # Phpmyadmin
    phpmyadmin:
        container_name: CPA-Phpmyadmin
        image: phpmyadmin:latest
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.phpmyadmin2.rule=Host(`scyba.com`)"
            - "traefik.http.routers.phpmyadmin2.entrypoints=phpmyadmin2"
            - "traefik.http.routers.phpmyadmin2.tls.certresolver=myresolver"
            - "traefik.http.services.phpmyadmin2.loadbalancer.server.port=80"
        environment:
            PMA_HOST: mysql
        depends_on:
            - mysql
        networks:
            - sail

# 2. Networks
networks:
    sail:
        driver: bridge

# 3. Volumes
volumes:
    sail-mysql:
        driver: local